CREATE DATABASE ASSIGNMENT;

USE ASSIGNMENT;

CREATE TABLE PRODUCTS (
    PRODUCT_ID INT PRIMARY KEY,
    NAME VARCHAR(100) NOT NULL,
    PRICE DECIMAL(10, 2),
    STOCK INT CHECK (STOCK >= 0)
);

CREATE TABLE CUSTOMERS (
    CUSTOMER_ID INT PRIMARY KEY,
    FIRST_NAME VARCHAR(50),
    LAST_NAME VARCHAR(50),
    EMAIL VARCHAR(100) UNIQUE,
    PHONE VARCHAR(15),
    AGE INT CHECK (AGE >= 18)
);

