CREATE DATABASE BOOKSTORES;
USE BOOKSTORES;
CREATE TABLE BOOKS (
  BOOK_ID INT NOT NULL UNIQUE,
  TITLE VARCHAR(100) NOT NULL UNIQUE,
  AUTHOR_ID INT NOT NULL,
  GENRE_ID INT NOT NULL,
  PRICE DECIMAL(10, 2) NOT NULL,
  PUBLICATION_DATE DATE NOT NULL,
  ISBN VARCHAR(20) NOT NULL UNIQUE
);

INSERT INTO BOOKS VALUES(1, "To Kill a Mockingbird", 1, 1, 15.99, "1960-07-11", "978-0061120084");
INSERT INTO BOOKS VALUES(2, "The Great Gatsby", 2, 1, 12.99, "1925-04-10", "978-0743273565");
INSERT INTO BOOKS VALUES(3, "Harry Potter", 3, 2, 19.99, "1997-06-26", "978-0439554930");
INSERT INTO BOOKS VALUES(4, "The Catcher in the Rye", 4, 3, 10.99, "1951-07-16", "978-0316769174");
INSERT INTO BOOKS VALUES(5, "Pride and Prejudice", 5, 4, 14.99, "1813-01-28", "978-1853260509");
INSERT INTO BOOKS VALUES(6, "The Catcher in Rye", 4, 3, 10.99, "1951-07-16", "968-0316769174");
INSERT INTO BOOKS VALUES(7, "Pride", 5, 4, 14.99, "1813-01-28", "968-1853260509");

SELECT * FROM BOOKS;

ALTER TABLE BOOKS ADD COLUMN Language VARCHAR(50);

RENAME TABLE BOOKS TO BOOK_COLLECTIONS;

SELECT * FROM BOOK_COLLECTIONS;

SELECT * FROM BOOK_COLLECTIONS WHERE BOOK_ID < 4;
SELECT * FROM BOOK_COLLECTIONS WHERE BOOK_ID > 2;
SELECT * FROM BOOK_COLLECTIONS WHERE BOOK_ID <= 4;
SELECT * FROM BOOK_COLLECTIONS WHERE BOOK_ID >= 2;
SELECT * FROM BOOK_COLLECTIONS WHERE BOOK_ID = 4;
SELECT * FROM BOOK_COLLECTIONS WHERE BOOK_ID != 5;
SELECT * FROM BOOK_COLLECTIONS WHERE NOT ISBN = 978-0061120084;
SELECT * FROM BOOK_COLLECTIONS WHERE TITLE='HARRY POTTER' AND BOOK_ID=3;
SELECT * FROM BOOK_COLLECTIONS WHERE TITLE='HARRY POTTER' OR BOOK_ID<3;
SELECT * FROM BOOK_COLLECTIONS WHERE BOOK_ID BETWEEN 1 AND 5;
SELECT * FROM BOOK_COLLECTIONS WHERE TITLE IN ('HARRY POTTER','To Kill a Mockingbird');

TRUNCATE TABLE BOOK_COLLECTIONS;

SHOW DATABASES;

SELECT user FROM mysql.user;



CREATE TABLE AUTHORS (
  AuthorID INT NOT NULL UNIQUE,
  Name VARCHAR(100) NOT NULL UNIQUE,
  Nationality VARCHAR(50) NOT NULL,
  BirthDate DATE NOT NULL,
  DeathDate DATE NOT NULL,
  FamousWork VARCHAR(100) NOT NULL,
  Awards VARCHAR(100) NOT NULL
);

INSERT INTO AUTHORS VALUES(1, 'Harper Lee', 'American', '1926-04-28', '2016-02-19', 'To Kill a Mockingbird', 'Pulitzer Prize');
INSERT INTO AUTHORS VALUES(2, 'F. Scott Fitzgerald', 'American', '1896-09-24', '1940-12-21', 'The Great Gatsby', 'None');
INSERT INTO AUTHORS VALUES(3, 'J.K. Rowling', 'British', '1965-07-31', '1941-12-21', 'Harry Potter', 'Numerous');
INSERT INTO AUTHORS VALUES(4, 'J.D. Salinger', 'American', '1919-01-01', '2010-01-27', 'The Catcher in the Rye', 'None');
INSERT INTO AUTHORS VALUES(5, 'Jane Austen', 'British', '1775-12-16', '1817-07-18', 'Pride and Prejudice', 'None');
INSERT INTO AUTHORS VALUES(6, 'Ragav', 'American', '1909-01-01', '2010-01-27', 'The Catcher in Rye', 'None');
INSERT INTO AUTHORS VALUES(7, 'Jane', 'British', '1775-12-16', '1817-07-18', 'Pride', 'None');

SELECT * FROM AUTHORS;

ALTER TABLE AUTHORS ADD COLUMN Biography TEXT;

RENAME TABLE AUTHORS TO AUTHORS1;

SELECT * FROM AUTHORS1;

SELECT * FROM AUTHORS1 WHERE AuthorID < 4;
SELECT * FROM AUTHORS1 WHERE AuthorID > 2;
SELECT * FROM AUTHORS1 WHERE AuthorID <= 4;
SELECT * FROM AUTHORS1 WHERE AuthorID >= 2;
SELECT * FROM AUTHORS1 WHERE AuthorID = 4;
SELECT * FROM AUTHORS1 WHERE AuthorID != 5;
SELECT * FROM AUTHORS1 WHERE NOT Name= 'Ragav';
SELECT * FROM AUTHORS1 WHERE Name ='Jane' AND AuthorID=7;
SELECT * FROM AUTHORS1 WHERE Name ='Jane' OR AuthorID=7;
SELECT * FROM AUTHORS1 WHERE AuthorID BETWEEN 1 AND 4;
SELECT * FROM AUTHORS1 WHERE Name IN ('Jane', 'British');

TRUNCATE TABLE AUTHORS1;

CREATE TABLE GENRES (
  GenreID INT NOT NULL UNIQUE,
  GenreName VARCHAR(50) NOT NULL UNIQUE,
  Description VARCHAR(255) NOT NULL,
  PopularBook VARCHAR(100) NOT NULL,
  PopularAuthor VARCHAR(100) NOT NULL,
  AgeGroup VARCHAR(50) NOT NULL,
  OriginDate DATE NOT NULL
);

INSERT INTO GENRES VALUES(1, 'Classic', 'Timeless literary works with enduring quality.', 'To Kill a Mockingbird', 'Harper Lee', 'Adults', '1800-01-01');
INSERT INTO GENRES VALUES(2, 'Fantasy', 'Fiction set in magical universes with supernatural elements.', 'Harry Potter', 'J.K. Rowling', 'All Ages', '1900-01-01');
INSERT INTO GENRES VALUES(3, 'Young Adult', 'Fiction targeted towards young adults and teens.', 'The Catcher in the Rye', 'J.D. Salinger', 'Teens', '1950-01-01');
INSERT INTO GENRES VALUES(4, 'Romance', 'Stories revolving around love and relationships.', 'Pride and Prejudice', 'Jane Austen', 'Adults', '1800-01-01');
INSERT INTO GENRES VALUES(5, 'Mystery', 'Fiction set in magical universes with supernatural elements.', 'Harry Potter', 'J.K. Rowling', 'All Ages', '1900-01-01');
INSERT INTO GENRES VALUES(6, 'Fiction', 'Fiction targeted towards young adults and teens.', 'The Catcher in Rye', 'J.D. Salinger', 'Teens', '1950-01-01');
INSERT INTO GENRES VALUES(7, 'Non Fiction', 'Stories revolving around love and relationships.', 'Pride', 'Jane Austen', 'Adults', '1800-01-01');

SELECT * FROM GENRES;

RENAME TABLE GENRES TO GENRESINFO;
 SELECT * FROM GENRESINFO;
ALTER TABLE GENRES ADD COLUMN PUBLISHERS varchar(50);

SELECT * FROM GENRESINFO WHERE GenreID < 4;
SELECT * FROM GENRESINFO WHERE GenreID > 2;
SELECT * FROM GENRESINFO WHERE GenreID <= 4;
SELECT * FROM GENRESINFO WHERE GenreID >= 2;
SELECT * FROM GENRESINFO WHERE GenreID = 4;
SELECT * FROM GENRESINFO WHERE GenreID != 5;
SELECT * FROM GENRESINFO WHERE NOT GenreName= 'FANTASY';
SELECT * FROM GENRESINFO WHERE GenreName ='non fiction' AND GenreID=7;
SELECT * FROM GENRESINFO WHERE GenreName ='fiction' OR GenreID<7;
SELECT * FROM GENRESINFO WHERE GenreID BETWEEN 1 AND 4;
SELECT * FROM GENRESINFO WHERE GenreName IN (6, 'fiction');

TRUNCATE TABLE GENRESINFO;




