CREATE DATABASE WORKSHOP;
USE WORKSHOP;
SET GLOBAL sql_mode=(SELECT REPLACE(@@sql_mode,'ONLY_FULL_GROUP_BY',''));
CREATE TABLE USER_INFO(
USER_NAME VARCHAR(25) NOT NULL,
USER_PHONE_NUMBER INT UNIQUE NOT NULL,
EMAIL VARCHAR(100) UNIQUE,
ADDRESS VARCHAR(100) NOT NULL,
AGE INT NOT NULL CHECK (AGE>18),
STATE VARCHAR(100) NOT NULL,
COUNTRY VARCHAR(200) DEFAULT 'INDIA',
AADHAR_NUMBER BIGINT NOT NULL,
USER_ID INT AUTO_INCREMENT PRIMARY KEY);

INSERT INTO USER_INFO(USER_NAME,CONTACT,EMAIL,ADDRESS,AGE,STATE,AADHAR_NUMBER) VALUES
('POOJA',9123456789,'POOJA@GMAIL.COM','BHADRAVATHI',19,'KARNATAKA',123456789012),
('POOJITHA',9123496789,'POO@GMAIL.COM','BHADRAVATHI',19,'KERALA',125456789012),
('VARSHA',9123406789,'VARSHA@GMAIL.COM','BHADRAVATHI',19,'KARNATAKA',126456789012),
('POOJA',9123451789,'POOJ@GMAIL.COM','BHADRAVATHI',19,'TAMILNADU',123756789012),
('PURVI',9123426789,'PURVI@GMAIL.COM','BHADRAVATHI',19,'TAMILNADU',123486789012);


SELECT * FROM USER_INFO;
ALTER TABLE USER_INFO CHANGE USER_PHONE_NUMBER CONTACT BIGINT;
TRUNCATE TABLE USER_INFO;
SELECT * FROM USER_INFO HAVING STATE='KARNATAKA'; 
SELECT COUNT(STATE) FROM USER_INFO GROUP BY STATE;
SELECT STATE,COUNT(STATE) FROM USER_INFO GROUP BY STATE;
SELECT STATE,COUNT(STATE) FROM USER_INFO GROUP BY STATE HAVING STATE="KARNATAKA";

SELECT STATE,USER_NAME,COUNT(STATE) FROM USER_INFO GROUP BY STATE HAVING STATE='KARNATAKA' AND USER_NAME='POOJA';



